# Government of Rwanda ERP - Payroll System

spring.application.name=payroll

spring.datasource.url=jdbc:postgresql://localhost:5432/erp_payroll_db
spring.datasource.username=postgres
spring.datasource.password=5Tr@wberry
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# ── JWT Configuration ────────────────────────
app.jwt.secret=U3VwZXJTZWN1cmVTaWduaW5nS2V5Rm9yUndhbmRhRVJQUGF5cm9sbFN5c3RlbTIwMjZSV0FOREExMjM0NTY3ODkwMTI=
app.jwt.expiration=86400000


app.institution.name=Rwanda Coding Academy (RCA)


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
