package rw.gov.erp.payroll.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import rw.gov.erp.payroll.dto.response.ApiResponse;
import rw.gov.erp.payroll.entity.Message;
import rw.gov.erp.payroll.service.MessageService;

import java.util.List;

/**
 * Task 5 – Message Controller
 * Messages are auto-generated by PostgreSQL trigger on payroll approval.
 * This controller provides READ access.
 */
@RestController
@RequestMapping("/api/messages")
@RequiredArgsConstructor
@Tag(name = "Messages", description = "Task 5 - View notification messages generated by DB trigger on payroll approval")
@SecurityRequirement(name = "bearerAuth")
public class MessageController {

    private final MessageService messageService;

    @Operation(
        summary = "Get all messages (ADMIN view)",
        description = "Returns all messages inserted by the PostgreSQL trigger when payroll was approved"
    )
    @GetMapping
    public ResponseEntity<ApiResponse<List<Message>>> getAllMessages() {
        return ResponseEntity.ok(ApiResponse.success("Messages retrieved", messageService.getAllMessages()));
    }

    @Operation(summary = "Get currently logged-in employee's messages")
    @GetMapping("/me")
    public ResponseEntity<ApiResponse<List<Message>>> getMyMessages() {
        org.springframework.security.core.Authentication auth = 
                org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();
        List<Message> messages = messageService.getMyMessages(auth.getName());
        return ResponseEntity.ok(ApiResponse.success("Your messages retrieved", messages));
    }

    @Operation(summary = "Get messages for a specific employee")
    @GetMapping("/employee/{employeeId}")
    public ResponseEntity<ApiResponse<List<Message>>> getByEmployee(@PathVariable Long employeeId) {
        return ResponseEntity.ok(ApiResponse.success("Employee messages retrieved",
                messageService.getMessagesByEmployee(employeeId)));
    }

    @Operation(
        summary = "Get messages for a specific month-year",
        description = "monthYear format: DECEMBER-2024"
    )
    @GetMapping("/period/{monthYear}")
    public ResponseEntity<ApiResponse<List<Message>>> getByPeriod(@PathVariable String monthYear) {
        return ResponseEntity.ok(ApiResponse.success("Period messages retrieved",
                messageService.getMessagesByMonthYear(monthYear)));
    }
}
