package rw.gov.erp.payroll.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Message entity – stores notification messages generated by the DB trigger.
 * Task 5: When ADMIN approves payroll, the PostgreSQL trigger inserts a message here.
 *
 * Format: "Dear <FIRSTNAME> Your salary of <MONTH/YEAR> from <INSTITUTION>
 *          <AMOUNT> FRW has been credited to your <EMPLOYEE_CODE> account Successfully."
 */
@Entity
@Table(name = "messages")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The employee this message belongs to */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", nullable = false)
    private Employee employee;

    /** Full message text */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    /** e.g. "DECEMBER-2024" */
    @Column(nullable = false)
    private String monthYear;

    /** Auto-set when trigger inserts the record */
    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;
}
